task:
  name: Build (Alpine Linux)
  container:
    image: alpine:3.17
    cpu: 8
  environment:
    PATH: "$HOME/.cargo/bin:$PATH"
  install_script:
    - apk add --update curl git gcc musl-dev sdl2-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain 1.61.0
    - rustup component add rustfmt
    - rustup target add thumbv7em-none-eabihf
  test_script:
    - cargo fmt -- --check
    - cargo test
    - cargo build --package profont --target thumbv7em-none-eabihf
